name: Go

on: [ 'push' ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: |
          go test -v ./... \
            && ./scripts/integration-test.sh

      - name: Build
        run: ./scripts/build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: windows-binaries
          path: bin/*-windows-*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: linux-binaries
          path: bin/*-linux-*

  package-deb:
    name: Package (debian)
    needs: build
    runs-on: ubuntu-latest
    container: debian:11.1-slim
    steps:
      - name: Setup dependency
        run: |
          apt-get -qq update \
            && apt-get -yqq -o=Dpkg::Use-Pty=0 --no-install-recommends install \
                build-essential \
                debhelper-compat \
                devscripts \
                git \
            && rm -rf /var/lib/apt/lists/*
      - name: package to deb
        working-directory: packaging/deb
        run: |
          debuild  -uc -us -Zxz -z9 \
            --lintian-opts \
              --profile debian \
              --suppress-tags statically-linked-binary
      - name: archive the deb package
        uses: actions/upload-artifact@v2.1.4
        with:
          name: deb package
          path: packaging/*.deb
